### ISSUE TITLE
Error attempt with raw data

### ISSUE THREAD

**Issue by caojl1994** [ToryDeng/scCTS#1]
Error attempt with raw data, Windows system    

Is it because of the system? Where does the built-in code need to be modified?

> data(sim.sce)
> res <- scCTS(sim.sce, subject.rep='subject', celltype.rep='celltype', numCores=1)

── scCTS analysis ───────────────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Start at `2024-11-03 21:52:47.245314`
错误于get.expression.matrix(sce, use.raw, use.norm.rep, normalize = TRUE): 
  不是所有的"normcounts" %in% assayNames(sce)都是TRUE

**Comment by ToryDeng** [comment]
By default, `scCTS` utilizes the normalized counts stored in `normcounts(sce)`. To address this issue, you can set `use.raw=TRUE` as shown below:

```r
library(scCTS)

data(sim.sce)
result <- scCTS(sim.sce, subject.rep='subject', celltype.rep='celltype', use.raw=TRUE, numCores=1)
 
```
